# Generated by Django 6.0.1 on 2026-01-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_key', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('custom_key', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ShortenedURL',
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_key'], name='shortener_s_short_k_59d80a_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['custom_key'], name='shortener_s_custom__a1429d_idx'),
        ),
    ]
