# Generated by Django 6.0.1 on 2026-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_delete_shortenedurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
