# Generated by Django 6.0.1 on 2026-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
